'use strict';

(function(){
	/**
	 * Login Controller for the form generated by the directive
	 */
	function loginController($scope, LoginServices){
		$scope.credentials = {
			user: '',
			password: ''
		};

		//Login method call from the ng-submit
		$scope.login = function () {
			$scope.error = "";
			if ($scope.credentials.user == ""){
				$scope.error = "User Invalid";
				return false;
			}else if($scope.credentials.password == ""){
				$scope.error = "Password Invalid";
				return false;
			}

			//Accessing the LoginServices to get try to login

			LoginServices.login($scope.credentials).then(function (user) {
				//Don't need to add much code, because is handled by $broadcast messages
				//All other information to the user should be done here, adding session variables for example  	
			}, function () {
				$scope.error = "Invalid login";
			});
		};
	}
	/**
	* Login Directive to handle the login component in the page. 
	* It could be added as a dialog
	*/
	function loginDirective(){
		return {
			restrict:'E',
			scope:{

			},
			templateUrl: 'scripts/directives/template/login-form.html'
		}
	}


	angular.module('myApp.directives', [])
	.controller('LoginController', loginController)
	.directive('loginForm', loginDirective);

})();